TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 4
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: False
  FINETUNE: True
DATA:
  PATH_TO_DATA_DIR: './video_outputs'
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.05
  LR_POLICY: cosine
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: adamw
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 25
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    GRAD_CAM:
      USE_TRUE_LABEL: True
  LOG_DIR: '/content/drive/MyDrive/Action_recognition/TimeSformer/logs/train_adam2'
  WRONG_PRED_VIS:
    ENABLE: True
  CONFUSION_MATRIX:
    ENABLE: True
    FIGSIZE: [8, 8]
  HISTOGRAM:
    ENABLE: True 
    FIGSIZE: [8, 8]
  CLASS_NAMES_PATH: '/content/drive/MyDrive/Action_recognition/TimeSformer/label_mapping.json'